version: '3.3'
networks:
  quangcao:
    driver: bridge
services:
  api:
    build:
      context: .
    image: lovehangga/ltct-btl
    depends_on:
      - db
      # - migration
    # links:
    #   - db:db
    environment:
      - DB_TYPE=postgres
      - DB_PORT=5432
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=gzr2efGPYs
      - DB_NAME=test
    networks:
      - quangcao
    ports:
      - 3000:3000
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gzr2efGPYs
      POSTGRES_DB: test
    ports:
      - 5433:5432
  # migration:
  #   image: lovehangga/ltct-btl
  #   command: npm typeorm migration:run
  #   depends_on:
  #     - db
  #   networks:
  #     - quangcao


